# Docker Compose configuration for production deployment using pre-built images
# This file uses the pre-built images from Docker Hub instead of building locally

version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  manticore:
    image: weli/manticoresearch-example:manticore
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "9306:9306"
      - "9308:9308"
    volumes:
      - ./manticore.conf:/etc/manticoresearch/manticore.conf
      - ./wordforms.txt:/etc/manticoresearch/wordforms.txt
      - manticore_data:/var/lib/manticore

  app:
    image: weli/manticoresearch-example:app
    depends_on:
      postgres:
        condition: service_healthy
      manticore:
        condition: service_started
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
      - "8080:8080"

volumes:
  postgres_data:
  manticore_data: 