name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
        
    - name: Download and set up Jieba dictionary
      run: |
        chmod +x download_dict.sh
        ./download_dict.sh
        
    - name: Build Docker images
      run: |
        docker-compose build || {
          echo "Build failed, showing logs:"
          docker-compose logs
          exit 1
        }
      
    - name: Start services
      run: |
        docker-compose up -d || {
          echo "Start services failed, showing logs:"
          docker-compose logs
          exit 1
        }
      
    - name: Wait for services to be ready
      run: |
        sleep 30
        docker-compose ps || {
          echo "Services not ready, showing logs:"
          docker-compose logs
          exit 1
        }
        
    - name: Make test scripts executable
      run: chmod +x test_web_search.sh test_mixed_search.sh
      
    - name: Run web search tests
      run: ./test_web_search.sh
      
    - name: Run mixed search tests
      run: ./test_mixed_search.sh
      
    - name: Clean up
      if: always()
      run: |
        docker-compose down -v 